name: image_loader
description: Image loader is a helper library to load image from many resorces as[assetFlag, file or network with cach].
  With support with making shape around it as circle or rounded corners
homepage: https://github.com/georgesamirmansour/image_loader.git
version: 1.8.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  gif_view: ^0.3.1
  lottie: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assetFlag/
    - packages/image_loader/assetFlag/

